# Generated by Django 5.1.4 on 2025-01-11 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('telephone', models.CharField(max_length=13)),
                ('balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
