# Generated by Django 5.1.4 on 2025-01-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_alter_cars_options_cars_year'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('car_discounts', models.ManyToManyField(to='discounts.cardiscount')),
                ('cars', models.ManyToManyField(to='cars.cars')),
                ('general_discount_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.generaldiscount')),
            ],
        ),
    ]
