# Generated by Django 5.1.4 on 2025-03-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('available_cars', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('car_discounts', models.ManyToManyField(to='discounts.cardiscount')),
                ('cars_in_stock', models.ManyToManyField(to='available_cars.availablecars')),
                ('general_discount_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.generaldiscount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
