# Generated by Django 5.2.8 on 2025-11-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='general_discount_id',
            new_name='general_discount',
        ),
    ]
