# Generated by Django 5.1.4 on 2025-01-13 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_is_active_alter_supplier_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='cars',
            new_name='cars_in_stock',
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
