[pytest]
env_files = .env
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests/*.py
addopts = -rP
django_debug_mode = True
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning