# Generated by Django 5.1.4 on 2025-01-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0003_autoshop_is_active_alter_autoshop_cars_in_stock'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generaldiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpersonaldiscount',
            name='autoshop_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop'),
        ),
        migrations.AddField(
            model_name='userpersonaldiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
