# Generated by Django 5.1.4 on 2025-03-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoshops', '0001_initial'),
        ('cars', '0001_initial'),
        ('discounts', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshoppersonaldiscount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='cardiscount',
            name='car',
            field=models.ManyToManyField(to='cars.car'),
        ),
        migrations.AddField(
            model_name='userpersonaldiscount',
            name='autoshop',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop'),
        ),
    ]
