# Generated by Django 5.1.4 on 2025-01-13 21:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0004_autoshop_created_at_autoshop_desired_brand_and_more'),
        ('cars', '0005_car_created_at_car_updated_at'),
        ('discounts', '0002_cardiscount_is_active_generaldiscount_is_active_and_more'),
        ('suppliers', '0003_rename_cars_supplier_cars_in_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonaldiscount',
            old_name='autoshop_id',
            new_name='autoshop',
        ),
        migrations.AddField(
            model_name='cardiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generaldiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaldiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userpersonaldiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpersonaldiscount',
            name='purchases_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpersonaldiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='cardiscount',
            name='car',
        ),
        migrations.CreateModel(
            name='AutoShopPersonalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('purchases_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshop', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cardiscount',
            name='car',
            field=models.ManyToManyField(to='cars.car'),
        ),
    ]
