# Generated by Django 5.2.8 on 2025-11-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiscount',
            old_name='car',
            new_name='cars',
        ),
    ]
