# Generated by Django 5.1.4 on 2025-01-14 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_rename_autoshop_id_userpersonaldiscount_autoshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshoppersonaldiscount',
            name='increasing_percent_per_requirements_fulfilled',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoshoppersonaldiscount',
            name='required_cars_bought_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
