# Generated by Django 5.1.4 on 2025-08-17 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoshops', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('desired_brand', models.CharField(max_length=50, null=True)),
                ('desired_mark', models.CharField(max_length=50, null=True)),
                ('min_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
