# Generated by Django 5.1.4 on 2025-01-13 21:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoshops', '0004_autoshop_created_at_autoshop_desired_brand_and_more'),
        ('suppliers', '0003_rename_cars_supplier_cars_in_stock_and_more'),
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShopToSupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('min_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('desired_brand', models.CharField(max_length=50, null=True)),
                ('desired_mark', models.CharField(max_length=50, null=True)),
                ('min_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserToAutoShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('min_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('desired_brand', models.CharField(max_length=50, null=True)),
                ('desired_mark', models.CharField(max_length=50, null=True)),
                ('min_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
