# Generated by Django 5.1.4 on 2025-01-14 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0005_remove_autoshop_min_price'),
        ('cars', '0005_car_created_at_car_updated_at'),
        ('offers', '0001_initial'),
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoautoshopoffer',
            name='autoshop',
        ),
        migrations.RemoveField(
            model_name='usertoautoshopoffer',
            name='user',
        ),
        migrations.CreateModel(
            name='AutoShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('desired_brand', models.CharField(max_length=50, null=True)),
                ('desired_mark', models.CharField(max_length=50, null=True)),
                ('min_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AutoShopToSupplierOffer',
        ),
        migrations.DeleteModel(
            name='UserToAutoShopOffer',
        ),
    ]
