# Generated by Django 5.2.8 on 2025-11-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoshopoffer',
            old_name='desired_mark',
            new_name='desired_model',
        ),
    ]
