# Generated by Django 5.2.7 on 2025-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoshopoffer',
            name='desired_mark',
        ),
        migrations.AddField(
            model_name='autoshopoffer',
            name='desired_model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
