# Generated by Django 5.1.4 on 2025-11-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoshopoffer',
            old_name='desired_mark',
            new_name='desired_model',
        ),
    ]
