# Generated by Django 5.1.4 on 2025-03-02 22:06

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('desired_brand', models.CharField(max_length=50, null=True)),
                ('desired_mark', models.CharField(max_length=50, null=True)),
                ('min_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_horsepower', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
