# Generated by Django 5.1.4 on 2025-01-11 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('buyers', models.ManyToManyField(to='users.user')),
            ],
        ),
    ]
