# Generated by Django 5.1.4 on 2025-08-17 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoshops', '0001_initial'),
        ('available_cars', '0001_initial'),
        ('discounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshop',
            name='buyers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='car_discounts',
            field=models.ManyToManyField(to='discounts.cardiscount'),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='cars_in_stock',
            field=models.ManyToManyField(to='available_cars.availablecars'),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='general_discount_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.generaldiscount'),
        ),
    ]
