# Generated by Django 5.1.4 on 2025-01-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoshops', '0001_initial'),
        ('cars', '0002_alter_cars_options_cars_year'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshop',
            name='car_discounts',
            field=models.ManyToManyField(to='discounts.cardiscount'),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='cars_in_stock',
            field=models.ManyToManyField(to='cars.cars'),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='general_discount_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.generaldiscount'),
        ),
    ]
