# Generated by Django 5.2.7 on 2025-12-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoshop',
            name='desired_mark',
        ),
        migrations.AddField(
            model_name='autoshop',
            name='desired_model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
