# Generated by Django 5.2.8 on 2025-11-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoshop',
            old_name='desired_mark',
            new_name='desired_model',
        ),
        migrations.RenameField(
            model_name='autoshop',
            old_name='general_discount_id',
            new_name='general_discount',
        ),
    ]
