# Generated by Django 5.1.4 on 2025-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0002_initial'),
        ('available_cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='autoshop',
            name='cars_in_stock',
            field=models.ManyToManyField(to='available_cars.availablecars'),
        ),
    ]
