# Generated by Django 5.1.4 on 2025-01-13 21:53

import django.core.validators
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0003_autoshop_is_active_alter_autoshop_cars_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoshop',
            name='desired_brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='desired_mark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='max_horsepower',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='max_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='max_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='min_horsepower',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='min_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='min_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='autoshop',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
