# Generated by Django 5.1.4 on 2025-01-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0004_autoshop_created_at_autoshop_desired_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoshop',
            name='min_price',
        ),
    ]
