# Generated by Django 5.1.4 on 2025-01-11 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Cars'},
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=1800, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
