# Generated by Django 5.2.7 on 2025-12-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
