# Generated by Django 5.1.4 on 2025-11-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mark',
            new_name='model',
        ),
    ]
