# Generated by Django 5.1.4 on 2025-01-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0002_initial'),
        ('cars', '0002_alter_cars_options_cars_year'),
        ('discounts', '0001_initial'),
        ('sales', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Cars', 'verbose_name_plural': 'Cars'},
        ),
    ]
