# Generated by Django 5.2.8 on 2025-11-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('available_cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablecars',
            old_name='car_id',
            new_name='car',
        ),
    ]
