# Generated by Django 5.2.8 on 2025-11-28 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_cars', '0002_rename_car_id_availablecars_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecars',
            name='last_purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
