name: Django CI
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - name: Create and setup .env file
        run: |
          cat > .env << EOF
          #POSTGRES
          DB_ENGINE=${{ secrets.DB_ENGINE || 'django.db.backends.postgresql' }}
          POSTGRES_NAME=${{ secrets.POSTGRES_NAME }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST || 'localhost' }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT || '5432' }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB || 'autoshop' }}

          #DJANGO
          DJANGO_IS_DEBUG=${{ secrets.DJANGO_IS_DEBUG || 'True' }}
          ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS || 'localhost,127.0.0.1,0.0.0.0' }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE || 'core.settings' }}
          BASE_URL=${{ secrets.BASE_URL || 'http://localhost:8000' }}
          LANGUAGE_CODE=${{ secrets.LANGUAGE_CODE || 'en-us' }}
          TIME_ZONE=${{ secrets.TIME_ZONE || 'UTC' }}
          USE_I18N=${{ secrets.USE_I18N || 'True' }}
          USE_TZ=${{ secrets.USE_TZ || 'True' }}

          #EMAIL
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          EMAIL_PORT=${{ secrets.EMAIL_PORT || '587' }}
          EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS || 'True' }}
          EMAIL_HOST=${{ secrets.EMAIL_HOST || 'smtp.yandex.ru' }}
          EMAIL_BACKEND=${{ secrets.EMAIL_BACKEND || 'django.core.mail.backends.smtp.EmailBackend' }}

          # ALLAUTH
          ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS=${{ secrets.ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS || '1' }}
          ACCOUNT_EMAIL_REQUIRED=${{ secrets.ACCOUNT_EMAIL_REQUIRED || 'True' }}
          ACCOUNT_EMAIL_VERIFICATION=${{ secrets.ACCOUNT_EMAIL_VERIFICATION || 'mandatory' }}
          ACCOUNT_AUTHENTICATION_METHOD=${{ secrets.ACCOUNT_AUTHENTICATION_METHOD || 'email' }}
          ACCOUNT_EMAIL_SUBJECT_PREFIX=${{ secrets.ACCOUNT_EMAIL_SUBJECT_PREFIX || 'AutoShop - ' }}
          ACCOUNT_DEFAULT_HTTP_PROTOCOL=${{ secrets.ACCOUNT_DEFAULT_HTTP_PROTOCOL || 'http' }}
          ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL=${{ secrets.ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL || '/api/users/email-verified/' }}
          ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL=${{ secrets.ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL || '/api/users/email-verified/' }}
          LOGIN_REDIRECT_URL=${{ secrets.LOGIN_REDIRECT_URL || '/api/user/' }}
          ACCOUNT_LOGOUT_REDIRECT_URL=${{ secrets.ACCOUNT_LOGOUT_REDIRECT_URL || '/api/users/login/' }}
          ACCOUNT_USERNAME_REQUIRED=${{ secrets.ACCOUNT_USERNAME_REQUIRED || 'False' }}
          ACCOUNT_UNIQUE_EMAIL=${{ secrets.ACCOUNT_UNIQUE_EMAIL || 'True' }}
          SITE_NAME=${{ secrets.SITE_NAME || 'AutoShop' }}
          SITE_ID=${{ secrets.SITE_ID || '1' }}

          # JWT
          ACCESS_TOKEN_LIFETIME_MINUTES=${{ secrets.ACCESS_TOKEN_LIFETIME_MINUTES || '60' }}
          REFRESH_TOKEN_LIFETIME_DAYS=${{ secrets.REFRESH_TOKEN_LIFETIME_DAYS || '1' }}
          ROTATE_REFRESH_TOKENS=${{ secrets.ROTATE_REFRESH_TOKENS || 'False' }}
          BLACKLIST_AFTER_ROTATION=${{ secrets.BLACKLIST_AFTER_ROTATION || 'True' }}
          JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM || 'HS256' }}
          JWT_AUTH_HEADER_TYPES=${{ secrets.JWT_AUTH_HEADER_TYPES || 'Bearer' }}
          JWT_AUTH_HEADER_NAME=${{ secrets.JWT_AUTH_HEADER_NAME || 'HTTP_AUTHORIZATION' }}
          JWT_USER_ID_FIELD=${{ secrets.JWT_USER_ID_FIELD || 'id' }}
          JWT_USER_ID_CLAIM=${{ secrets.JWT_USER_ID_CLAIM || 'user_id' }}

          # REST AUTH
          REST_AUTH_USE_JWT=${{ secrets.REST_AUTH_USE_JWT || 'True' }}
          REST_AUTH_JWT_HTTPONLY=${{ secrets.REST_AUTH_JWT_HTTPONLY || 'False' }}
          REST_AUTH_JWT_COOKIE=${{ secrets.REST_AUTH_JWT_COOKIE || 'autoshop-auth' }}
          REST_AUTH_JWT_REFRESH_COOKIE=${{ secrets.REST_AUTH_JWT_REFRESH_COOKIE || 'autoshop-refresh' }}
          EOF
          
      - name: Create virtual environment
        run: |
          python -m venv venv
      - name: Install Dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Print all environment variables
        run: cat .env
      - name: Run Django Tests
        run: |
          source venv/bin/activate
          pytest -v --ds=core.settings
        env:
          DATABASE_URL: postgres://postgres:root@localhost:5432/autoshop
      - name: Analysing the code with pylint
        run: |
          pylint *.py
      - name: Analysing the code with isort
        run: |
          isort *.py
      - name: Analysing the code with mypy
        run: |
          mypy .
      - name: Analysing the code with flake8
        run: |
          flake8 *.py
      - name: Build and run Docker containers
        run: |
           docker compose up -d --build