# Generated by Django 5.1.4 on 2025-01-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoshops', '0002_initial'),
        ('cars', '0002_alter_cars_options_cars_year'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShopSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.FloatField()),
                ('price', models.FloatField()),
                ('discount_percent', models.FloatField()),
                ('discount_amount', models.FloatField()),
                ('date', models.DateField()),
                ('autoshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.FloatField()),
                ('price', models.FloatField()),
                ('discount_percent', models.FloatField()),
                ('discount_amount', models.FloatField()),
                ('date', models.DateField()),
                ('autoshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshops.autoshop')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
