# Generated by Django 5.2.8 on 2025-11-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoshopsale',
            old_name='autoshop_id',
            new_name='autoshop',
        ),
        migrations.RenameField(
            model_name='suppliersale',
            old_name='autoshop_id',
            new_name='autoshop',
        ),
        migrations.RenameField(
            model_name='suppliersale',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
