# Generated by Django 5.1.4 on 2025-01-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0002_initial'),
        ('cars', '0003_rename_cars_car_alter_car_options'),
        ('sales', '0002_initial'),
        ('suppliers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoShopSales',
            new_name='AutoShopSale',
        ),
        migrations.RenameModel(
            old_name='SupplierSales',
            new_name='SupplierSale',
        ),
    ]
