# Generated by Django 5.2.8 on 2025-11-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_autoshop_id_autoshopsale_autoshop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshopsale',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suppliersale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
