# Generated by Django 5.2.8 on 2025-11-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_autoshopsale_date_alter_suppliersale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoshopsale',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='autoshopsale',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='suppliersale',
            old_name='car_id',
            new_name='car',
        ),
    ]
