# Generated by Django 5.1.4 on 2025-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_autoshopsales_autoshopsale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoshopsale',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='autoshopsale',
            name='start_price',
        ),
        migrations.RemoveField(
            model_name='suppliersale',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='suppliersale',
            name='start_price',
        ),
        migrations.AddField(
            model_name='autoshopsale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliersale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
