# Generated by Django 5.1.4 on 2025-01-13 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_autoshopsale_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshopsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoshopsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suppliersale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliersale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
